#Para Analizi Verileri
#Sat Aug 15 18:40:14 GMT+03:00 2026
beklenenKartBorcu=13734.0
donguBaslangic=2026-08-15
donguGeliri=0
kartBorcu=0
kurulumTamamlandi=evet
maas=35000.0
nakit=805.0
papara=334.0
ziraat=21113.0
